version: "3.8"

services:

  user-service:
    image: sharansc/user-service:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - freightiq-net

  shipment-service:
    image: sharansc/shipment-service:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SHIPMENT_SERVICE_PORT: ${SHIPMENT_SERVICE_PORT}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    depends_on:
      - user-service
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - freightiq-net

  ml-service:
    image: sharansc/ml-service:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      ML_SERVICE_PORT: ${ML_SERVICE_PORT}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      SHIPMENT_SERVICE_URL: ${SHIPMENT_SERVICE_URL}
    depends_on:
      - user-service
      - shipment-service
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: 500M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - freightiq-net

  frontend:
    image: sharansc/freight-frontend:latest
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      VITE_USER_SERVICE_URL: ${VITE_USER_SERVICE_URL}
      VITE_SHIPMENT_SERVICE_URL: ${VITE_SHIPMENT_SERVICE_URL}
      VITE_ML_SERVICE_URL: ${VITE_ML_SERVICE_URL}
    depends_on:
      - user-service
      - shipment-service
      - ml-service
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - freightiq-net

networks:
  freightiq-net:
    driver: bridge