server:
  port: ${USER_SERVICE_PORT:8080}

spring:
  application:
    name: User_Service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  jackson:
    deserialization:
      fail-on-null-for-primitives: false

app:
  cors:
    allowed-origins: ${FRONTEND_URL}