spring:
  application:
    name: User_Service

  datasource:
    url: "jdbc:postgresql://localhost:5432/FreightIQ"
    username: postgres
    password: Sharan@2005

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect