server:
  port: 8081

spring:
  application:
    name: ShipmentService

  datasource:
    url: "jdbc:postgresql://localhost:5432/FreightIQ"
    username: postgres
    password: Sharan@2005

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    deserialization:
      fail-on-null-for-primitives: false

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

user-service:
  url: http://localhost:8080