# Stage 1: Build React app
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .


ARG VITE_USER_SERVICE_URL
ARG VITE_SHIPMENT_SERVICE_URL
ARG VITE_ML_SERVICE_URL

ENV VITE_USER_SERVICE_URL=$VITE_USER_SERVICE_URL
ENV VITE_SHIPMENT_SERVICE_URL=$VITE_SHIPMENT_SERVICE_URL
ENV VITE_ML_SERVICE_URL=$VITE_ML_SERVICE_URL

RUN npm run build


FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Custom nginx config
COPY nginx.config /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]