server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # User Service
    location /api/user/ {
        rewrite ^/api/user/(.*)$ /api/$1 break;
        proxy_pass http://user-service:8080;
    }

    # Shipment Service
    location /api/shipment/ {
        rewrite ^/api/shipment/(.*)$ /api/$1 break;
        proxy_pass http://shipment-service:8081;
    }

    # ML Service
    location /api/ml/ {
        rewrite ^/api/ml/(.*)$ /api/$1 break;
        proxy_pass http://ml-service:8000;
    }
}